export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_LOADING = "CART_LOADING";
export const CART_LOADING_FAILED = "CART_LOADING_FAILED";
export const ADD_CART = "ADD_CART";
export const REDUCE_QUANTITY = "REDUCE_QUANTITY"
export const INCREASE_QUANTITY = "INCREASE_QUANTITY"