export const ADD_COMMENTS = "ADD_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const COMMENTS_LOADING_FAILED = "COMMENTS_LOADING_FAILED";