export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_LOADING_FAILED = "PRODUCTS_LOADING_FAILED";
export const ADD_CATEGORIES = "ADD_CATEGORIES";