export const USER_LOGIN = "USER_LOGIN";
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_LOGIN_FAILED = "USER_AUTH_FAILED";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOADING = "USER_LOADING";
export const USER_RESET = "USER_RESET";
export const UPDATE_USER_PROFILE_URI = "UPDATE_USER_PROFILE_URI"; 