export const ADD_WISHLIST = "ADD_WISHLIST";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const WISHLIST_LOADING = "WISHLIST_LOADING";
export const WISHLIST_LOADING_FAILED = "WISHLIST_LOADING_FAILED";